# use a node image as the base image and name it 'build' for
# later reference
FROM node:20 AS build
# set the working directory to /app
WORKDIR /app
# copy the current directory contents into the container at /app
#COPY package*.json /app/
#RUN npm cache clean --force
#RUN npm install
COPY . .
# install dependencies, matching package-lock.json
RUN npm ci
# build the app
RUN npm run build
#CMD ["/bin/sleep","infinity"]


# Use the latest version of the official Nginx image as the base image
FROM scratch AS export-stage
# copy the custom nginx configuration file to the container in the default
# location
#COPY nginx.conf /etc/nginx/nginx.conf
#WORKDIR /app
#ADD . /app/
# copy the built application from the build stage to the nginx html
# directory
COPY --from=build /app/dist/web/ .

# The above commands build the Angular app and then configure and build a
# Docker image for serving it using the nginx web server.
#RUN apt update
#RUN apt install snapd -y
